import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin, AiFillGithub, AiFillInstagram} from 'react-icons/ai'
import Image from 'next/image';
import deved from '../public/dev-ed.png'

export default function Home() {
  return (
    <div>

      <Head>
        <title> Quinn Landry Portfolio </title>
        <meta name='description' content='Generated by'/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>
    
      <main className='bg-slate-500 px-10'>

        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl text-slate-300'> Portfolio </h1>
            <ul className='flex items-center'>
              <li>
                <a 
                className='bg-gradient-to-r from-slate-600 to-slate-700 text-slate-300
                 px-4 py-2 rounded-md ml-8' href='#'
                 > 
                 Resume </a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-slate-300 font-medium'> Quinn Landry </h2>
            <h3 className='text-2xl py-2'> Fullstack Developer </h3>
            <p className='text-md py-5 leading-8 text-gray-800'>
              Description
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-slate-300'>
            <a target='_blank' href='https://www.linkedin.com/in/quinn-landry/'> <AiFillLinkedin/> </a>
            <a target='_blank'href='https://github.com/qrlandry'> <AiFillGithub /> </a>
            <a target='_blank' href='#'> <AiFillInstagram /> </a>
          </div>
          <div className='relative mx-auto rounded-full overflow-hidden w-80 h-80 mt-5'>
            <Image src={deved} layout='fill' objectFit='cover' />
          </div>
        </section>

        <section>
          <div className='text-center mt-20'>
            <h3 className='text-3xl py-1'> Skills </h3>
            <p className='text-md text-gray-800 py-2 leading-8'>
               Throughout my cohort at General Assembly I learned a numerous amount of skills
               such as: Html, CSS, Node.js, Django, Python, Javascript, React and Postgresql.
               I also have knowledge in Java, C and DrRacket.
            </p>
          </div>
        </section>
        <section>
          <div className='mt-20'>
            <h3 className='text-3xl py-1'> Projects </h3>
            <p className='text-md py-5 leading-8 text-gray-800'>
              Description
            </p>
          </div>

        </section>
      </main>
    </div>
  )
}
